import React, { useState, useEffect, useMemo, useRef } from "react";
import { Document, Page, pdfjs } from "react-pdf";
import {
  Download,
  Printer,
  ZoomIn,
  ZoomOut,
  ChevronLeft,
  ChevronRight,
  Maximize2,
  Minimize2,
  FileText,
  Loader2,
  AlertCircle,
  Sparkles,
} from "lucide-react";
import { toast } from "sonner";

// Configure pdfjs worker to reliably load in modern browser environments
if (typeof window !== "undefined" && !pdfjs.GlobalWorkerOptions.workerSrc) {
  pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
}

export interface PDFPreviewProps {
  /** PDF Blob, Blob URL, or base64 file data */
  file: Blob | string | null;
  /** Suggested download filename */
  fileName?: string;
  /** Document title or badge label */
  title?: string;
  /** Secondary subtitle or format note */
  subtitle?: string;
  /** Custom download handler */
  onDownload?: () => void;
  /** Custom print handler */
  onPrint?: () => void;
  /** Container CSS classes */
  className?: string;
}

export const PDFPreview: React.FC<PDFPreviewProps> = ({
  file,
  fileName = "Document_Resume.pdf",
  title = "PDF Preview",
  subtitle = "Generated by 10-Year Recruiter AI Engine",
  onDownload,
  onPrint,
  className = "",
}) => {
  const [numPages, setNumPages] = useState<number>(1);
  const [pageNumber, setPageNumber] = useState<number>(1);
  const [scale, setScale] = useState<number>(1.0);
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [isPrinting, setIsPrinting] = useState<boolean>(false);
  const printIframeRef = useRef<HTMLIFrameElement | null>(null);

  // Convert Blob to stable object URL
  const fileUrl = useMemo(() => {
    if (!file) return null;
    if (typeof file === "string") return file;
    try {
      return URL.createObjectURL(file);
    } catch {
      return null;
    }
  }, [file]);

  // Clean up object URL when component unmounts or file changes
  useEffect(() => {
    return () => {
      if (fileUrl && fileUrl.startsWith("blob:")) {
        URL.revokeObjectURL(fileUrl);
      }
    };
  }, [fileUrl]);

  // Handle successful document load
  const onDocumentLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
    setPageNumber(1);
    setLoadError(null);
  };

  const onDocumentLoadError = (err: Error) => {
    console.warn("[react-pdf] Document render note:", err.message);
    setLoadError(err.message || "Failed to load PDF document.");
  };

  const handleZoomIn = () => setScale(prev => Math.min(prev + 0.15, 2.2));
  const handleZoomOut = () => setScale(prev => Math.max(prev - 0.15, 0.6));
  const handleResetZoom = () => setScale(1.0);

  const handlePrevPage = () => setPageNumber(prev => Math.max(prev - 1, 1));
  const handleNextPage = () => setPageNumber(prev => Math.min(prev + 1, numPages));

  // Download PDF Handler
  const handleDownload = () => {
    if (onDownload) {
      onDownload();
      return;
    }

    if (!fileUrl) {
      toast.error("No PDF file ready for download.");
      return;
    }

    try {
      const a = document.createElement("a");
      a.href = fileUrl;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      toast.success(`Downloading ${fileName}...`);
    } catch (err: any) {
      console.error("[PDFPreview] Download error:", err);
      toast.error("Failed to trigger download. Please try printing to PDF instead.");
    }
  };

  // Direct Print PDF Handler
  const handlePrint = () => {
    if (onPrint) {
      onPrint();
      return;
    }

    if (!fileUrl) {
      toast.error("No PDF file available to print.");
      return;
    }

    setIsPrinting(true);
    toast.info("Preparing document for printing...");

    try {
      let iframe = printIframeRef.current;
      if (!iframe) {
        iframe = document.createElement("iframe");
        iframe.style.position = "fixed";
        iframe.style.right = "0";
        iframe.style.bottom = "0";
        iframe.style.width = "0";
        iframe.style.height = "0";
        iframe.style.border = "0";
        document.body.appendChild(iframe);
        printIframeRef.current = iframe;
      }

      iframe.src = fileUrl;
      iframe.onload = () => {
        setTimeout(() => {
          try {
            iframe?.contentWindow?.focus();
            iframe?.contentWindow?.print();
          } catch (e) {
            window.print();
          } finally {
            setIsPrinting(false);
          }
        }, 400);
      };
    } catch (err) {
      console.warn("[PDFPreview] Print iframe fallback:", err);
      window.print();
      setIsPrinting(false);
    }
  };

  if (!file) {
    return (
      <div className="flex flex-col items-center justify-center p-12 text-center rounded-3xl bg-white/40 border border-white/60 backdrop-blur-md">
        <div className="w-12 h-12 rounded-full glass-icon-circle bg-white/70 mb-3">
          <FileText className="w-6 h-6 text-[#C78997]" />
        </div>
        <p className="text-xs text-[#695B60] font-bold">No PDF document loaded</p>
      </div>
    );
  }

  return (
    <div
      className={`rounded-3xl border border-white/70 bg-white/40 backdrop-blur-2xl overflow-hidden flex flex-col shadow-[0_20px_60px_rgba(199,137,151,0.2)] ${
        isFullscreen ? "fixed inset-4 z-50 shadow-[0_30px_90px_rgba(199,137,151,0.4)]" : ""
      } ${className}`}
    >
      {/* Top Toolbar */}
      <div className="bg-white/60 border-b border-white/70 p-3.5 flex flex-wrap items-center justify-between gap-3 text-xs">
        {/* Document Title & Badge */}
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl glass-icon-circle bg-white/80 border border-white flex items-center justify-center text-[#C78997] shadow-[0_2px_10px_rgba(245,178,151,0.3)]">
            <Sparkles className="w-4 h-4 text-[#C78997]" />
          </div>
          <div>
            <span className="font-extrabold text-[#2A2125] block text-xs tracking-tight">{title}</span>
            <span className="text-[10px] text-[#695B60] block -mt-0.5">{subtitle}</span>
          </div>
        </div>

        {/* View Controls: Zoom, Pagination, and Action Buttons */}
        <div className="flex items-center flex-wrap gap-2 ml-auto">
          {/* Pagination Controls */}
          {numPages > 1 && (
            <div className="flex items-center bg-white/70 rounded-xl border border-white/80 px-1 py-0.5 shadow-sm">
              <button
                type="button"
                onClick={handlePrevPage}
                disabled={pageNumber <= 1}
                className="p-1 text-[#695B60] hover:text-[#C78997] disabled:opacity-30 transition-colors"
                title="Previous Page"
              >
                <ChevronLeft className="w-3.5 h-3.5" />
              </button>
              <span className="px-2 text-[10px] font-mono text-[#2A2125] font-bold">
                {pageNumber} / {numPages}
              </span>
              <button
                type="button"
                onClick={handleNextPage}
                disabled={pageNumber >= numPages}
                className="p-1 text-[#695B60] hover:text-[#C78997] disabled:opacity-30 transition-colors"
                title="Next Page"
              >
                <ChevronRight className="w-3.5 h-3.5" />
              </button>
            </div>
          )}

          {/* Zoom In/Out */}
          <div className="flex items-center bg-white/70 rounded-xl border border-white/80 px-1 py-0.5 shadow-sm">
            <button
              type="button"
              onClick={handleZoomOut}
              className="p-1 text-[#695B60] hover:text-[#C78997] transition-colors"
              title="Zoom Out"
            >
              <ZoomOut className="w-3.5 h-3.5" />
            </button>
            <button
              type="button"
              onClick={handleResetZoom}
              className="px-1.5 text-[10px] font-mono text-[#2A2125] font-bold hover:text-[#C78997]"
              title="Reset Zoom (100%)"
            >
              {Math.round(scale * 100)}%
            </button>
            <button
              type="button"
              onClick={handleZoomIn}
              className="p-1 text-[#695B60] hover:text-[#C78997] transition-colors"
              title="Zoom In"
            >
              <ZoomIn className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Fullscreen Toggle */}
          <button
            type="button"
            onClick={() => setIsFullscreen(prev => !prev)}
            className="p-1.5 rounded-xl bg-white/70 hover:bg-white text-[#695B60] border border-white/80 hover:text-[#2A2125] transition-colors shadow-sm"
            title={isFullscreen ? "Exit Fullscreen" : "Fullscreen Preview"}
          >
            {isFullscreen ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
          </button>

          {/* PRINT BUTTON */}
          <button
            id="pdfPrintBtn"
            type="button"
            onClick={handlePrint}
            disabled={isPrinting}
            className="button-glow px-3.5 py-1.5 rounded-2xl btn-sunset-glass text-xs font-extrabold inline-flex items-center gap-1.5 transition-all shadow-sm"
            title="Print this CV or save as PDF via system dialog"
          >
            {isPrinting ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin text-[#C78997]" />
            ) : (
              <Printer className="w-3.5 h-3.5 text-[#C78997]" />
            )}
            <span>Print</span>
          </button>

          {/* DOWNLOAD PDF BUTTON */}
          <button
            id="pdfDownloadBtn"
            type="button"
            onClick={handleDownload}
            className="button-glow px-4 py-1.5 rounded-2xl btn-sunset-rose text-xs font-black inline-flex items-center gap-1.5 shadow-[0_4px_15px_rgba(199,137,151,0.35)]"
            title="Download vector PDF file directly"
          >
            <Download className="w-3.5 h-3.5 text-white" />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      {/* PDF Document Canvas Viewport */}
      <div className="flex-1 overflow-auto bg-amber-50/20 p-4 sm:p-6 flex items-center justify-center min-h-[460px] max-h-[750px]">
        {fileUrl && (
          <Document
            file={fileUrl}
            onLoadSuccess={onDocumentLoadSuccess}
            onLoadError={onDocumentLoadError}
            loading={
              <div className="flex flex-col items-center justify-center py-20 text-[#695B60]">
                <Loader2 className="w-8 h-8 animate-spin text-[#C78997] mb-3" />
                <span className="text-xs font-bold">Rendering Vector PDF with react-pdf...</span>
              </div>
            }
            error={
              <div className="flex flex-col items-center justify-center py-16 text-center text-[#695B60]">
                <AlertCircle className="w-8 h-8 text-[#C78997] mb-2" />
                <span className="text-xs font-bold text-[#2A2125] mb-1">Interactive Viewer Ready</span>
                <span className="text-[11px] max-w-sm mb-4">
                  Your PDF is fully compiled and ready for direct printing or download.
                </span>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handlePrint}
                    className="button-glow px-4 py-2 rounded-2xl btn-sunset-glass text-xs font-bold inline-flex items-center gap-1.5 shadow-sm"
                  >
                    <Printer className="w-3.5 h-3.5 text-[#C78997]" />
                    <span>Print</span>
                  </button>
                  <button
                    type="button"
                    onClick={handleDownload}
                    className="button-glow px-4 py-2 rounded-2xl btn-sunset-rose text-xs font-black inline-flex items-center gap-2 text-white"
                  >
                    <Download className="w-3.5 h-3.5 text-white" />
                    <span>Download PDF Document</span>
                  </button>
                </div>
              </div>
            }
            className="shadow-2xl rounded-xl overflow-hidden border border-white bg-white"
          >
            <Page
              pageNumber={pageNumber}
              scale={scale}
              renderTextLayer={true}
              renderAnnotationLayer={false}
              className="max-w-full"
            />
          </Document>
        )}
      </div>

      {/* Bottom Status Bar */}
      <div className="bg-white/60 border-t border-white/70 px-4 py-2 flex items-center justify-between text-[11px] text-[#695B60]">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#C78997] animate-pulse" />
          <span className="font-semibold">100% Selectable Text (ATS-Compliant)</span>
        </div>
        <div className="flex items-center gap-3 font-medium">
          <span>Standard A4 Format</span>
          <span>·</span>
          <span>{fileName}</span>
        </div>
      </div>
    </div>
  );
};
